### ISSUE TITLE
bad_alloc error for FastText

### ISSUE THREAD

**Issue by kvtoraman** [FredericGodin/TwitterEmbeddings#2]
word2vec example worked fine but I got error when I tried fasttext.
I get `std::bad_alloc` when I try to run fasttext. It happens after I input the word.
Output:
```Query word? 	runningz
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    22214 abort (core dumped)  fasttext nn fasttext_twitter_raw.bin
```
I have 32G ram, on Ubuntu 16.04. 
Any suggestions? :thinking:

**Comment by FredericGodin** [comment]
Did you Google it?
https://github.com/facebookresearch/fastText/issues/40

**Comment by kvtoraman** [comment]
Thanks for the link. But I think my problem is different. The issue in the link is about training a model. In my case, I just query your model with `nn`. 
The argument `-bucket` is used during training stage. `nn` doesn't accept `-bucket` -it accepts 2 arguments only: _model_ and _k_
Can you tell me what I miss?

**Comment by FredericGodin** [comment]
I did a fresh clone and make of the FastText repo and downloaded the model, on my local machine with 16 GB of memory and I was able to use the model...

 ```
./fasttext nn ../fasttext_twitter_raw.bin
Query word? walking
walking-walking 0.816923
walkind 0.798055
walkin 0.790239
walkig 0.778558
walkings 0.776253
walkinh 0.775163
{walking 0.766358
twalking 0.762799
walking} 0.756438
walkinn 0.740855
```

**Comment by kvtoraman** [comment]
It worked for me as well :)
I restarted my computer, I guess that solved my memory issues.
Thanks for your help!
